# Generated by Django 3.1.6 on 2021-02-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aeg', '0002_bow_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='essays',
            name='topic',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='aeg.topics'),
        ),
    ]
